### ISSUE TITLE
Hyperparameter configuration of known gravity direction in OmniScenes dataset

### ISSUE THREAD

**Issue by wendaodi** [82magnolia/piccolo#4]
Hi，
I don't quite understand how to set the OmniScenes's hyperparameter. I have tried `xy_only = False, yaw_only = True` and `xy_only = True,yaw_only = True`. But they didn't achieve ideal accuracy.The other hyperparameters are set as follows.
```
[Dataset]
dataset = Omniscenes
sample_rate = 1
sharpen_color = True
num_bins = 256
out_of_room_quantile = 0.05
area = change_handheld
room_name = None

[Initialization]
num_trans = 50
xy_only = False/True
yaw_only = True
num_yaw = 8
num_roll = 4
num_pitch = 4
criterion = loss_histogram
num_intermediate = 50
num_input = 6
num_split_h = 4
num_split_w = 4
trans_init_mode = uniform

[Train]
lr = 0.1
num_iter = 100
patience = 5
factor = 0.8
loss_type = sampling

[Visualization]
visualize = False

[Parallel]
parallel = True
```

**Comment by 82magnolia** [comment]
Hello, sorry for the late reply. I just fixed the code to include configs and loading scripts for omniscenes. You can try it out with the following command: `python main.py --config configs/omniscenes.ini --log log/test`. Also, the results in our original paper was obtained using the older version of OmniScenes. Which version of OmniScenes did you use in your original set of experiments?

**Comment by wendaodi** [comment]
Hi, thank you very much for your reply. I used `omniscenes_ver_1_1_release/change_handheld_pano/` which in DropBox link for my experiments. Is it the older version of OmniScenes used in your paper?

**Comment by 82magnolia** [comment]
Aha I see. It seems that that the OmniScenes version is correct then. Could you try running a new set of experiments in omniscenes using the command above? For running on 'change_handheld_pano' you may need to fix the command as follows: `python main.py --config configs/omniscenes.ini --log log/test --override 'split_name=change_handheld'`.

**Comment by wendaodi** [comment]
To save time, I ran PICCOLO only in `omniscenes_ver_1_1_release/change_handheld_pano/`. It has an accuracy of 0.255 with `xy_only = True,yaw_only = True` and 0.267 with `xy_only = False, yaw_only = True` by running with my original config. Also, I run a new set of experiments in `omniscenes_ver_1_1_release/change_handheld_pano/` using the command above. But its accuracy was only 0.261.
(I notice that the number of `omniscenes_ver_1_1_release ` differs from that indicated in the supplementary material.)

**Comment by 82magnolia** [comment]
Sorry for the late reply. I ran a few experiments and indeed, I was also getting a similar accuracy as yours (~0.26 in `change_handheld_pano`). After carefully comparing the released code against our internal version, I found that there were a few commits that have not been incorporated in the release. Now the updated code is available, and I believe you can achieve an accuracy of around (0.46) in `change_handheld_pano`. Regarding your last point, the number of images in the released dataset is different from that in the supplementary material as we removed images whose pose labels are incorrect or those that  largely contain the school logo.

**Comment by wendaodi** [comment]
Thank you very much for your help, I have achieved an accuracy of around (0.46) in `change_handheld_pano`. PICCOLO is a really good work.
